# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: c
sudo: required
script:
  - autoreconf -iv
  - ./configure
  - make check
  - cd test; python setup.py test; cd..; return 0

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

notifications:
  email: false

matrix:
  allow_failures:
    - os: osx

